mod attention;
mod encoder;
mod model;
mod tensor;
mod tokenizer;
mod trainer;

use model::{SentenceEmbeddingResult, SentenceTransformer};
use std::env;
use std::fs::File;
use std::io::{self, BufRead, Write};
use tokenizer::SimpleTokenizer;
use trainer::{get_sample_dataset, train_poc_sentence_transformer};

fn build_and_train_model() -> SentenceTransformer {
    let mut tokenizer = SimpleTokenizer::new();

    // Collect initial vocabulary from sample pairs
    let sample_data = get_sample_dataset();
    let mut corpus: Vec<&str> = Vec::new();
    for pair in &sample_data {
        corpus.push(pair.sent_a);
        corpus.push(pair.sent_b);
    }
    // Add extra common domain vocabulary
    corpus.push("transformer multi head self attention query key value vector embeddings");
    corpus.push("natural language processing dense representations cosine similarity semantic search");
    corpus.push("rust high performance memory safe systems programming machine learning");

    tokenizer.build_vocab(&corpus);

    // Hyperparameters for our POC Sentence Transformer
    let d_model = 64; // Embedding dimension
    let num_heads = 4; // 4 attention heads (d_k = 16 per head)
    let d_ff = 128; // Feed-forward hidden dimension
    let num_layers = 2; // 2 stacked Transformer Encoder layers
    let max_seq_len = 32; // Maximum tokens per sentence

    let mut model = SentenceTransformer::new(
        tokenizer,
        d_model,
        num_heads,
        d_ff,
        num_layers,
        max_seq_len,
    );

    // Run POC training for 200 epochs (demonstrating loss convergence across iterations)
    train_poc_sentence_transformer(&mut model, 200, 0.05);

    model
}

/// Save embeddings to both formatted JSON and human-readable Markdown/Text files
fn save_embeddings_to_files(
    results: &[SentenceEmbeddingResult],
    similarities: &[(String, String, f32)],
) -> io::Result<()> {
    // 1. JSON file
    let json_file_path = "embeddings_output.json";
    let json_file = File::create(json_file_path)?;
    serde_json::to_writer_pretty(json_file, &results)?;
    println!(" [FILE SAVED] Full raw embeddings saved to: {}", json_file_path);

    // 2. Markdown / Text file for presentation
    let md_file_path = "embeddings_output.md";
    let mut md_file = File::create(md_file_path)?;

    writeln!(md_file, "# Sentence Transformer - Embeddings Output Log")?;
    writeln!(md_file, "Generated by: Pure Rust Transformer Proof-of-Concept\n")?;
    writeln!(md_file, "## Model Architecture Details")?;
    writeln!(md_file, "- **Type**: Encoder-only Sentence Transformer (MiniLM-style)")?;
    writeln!(md_file, "- **Model Dimension ($d_{{model}}$)**: 64")?;
    writeln!(md_file, "- **Attention Heads**: 4 ($d_k = 16$)")?;
    writeln!(md_file, "- **Encoder Layers**: 2")?;
    writeln!(md_file, "- **Pooling**: Mean Pooling over active tokens + L2 Normalization")?;
    writeln!(md_file, "- **Vector Space**: Unit Hypersphere ($||v||_2 = 1.0$)\n")?;
    writeln!(md_file, "---\n")?;

    writeln!(md_file, "## Generated Sentence Embeddings\n")?;

    for (idx, res) in results.iter().enumerate() {
        writeln!(md_file, "### Sentence #{}: \"{}\"", idx + 1, res.text)?;
        writeln!(md_file, "- **Tokenized Sequence**: `{:?}`", res.tokens)?;
        writeln!(md_file, "- **Token IDs**: `{:?}`", res.token_ids)?;
        writeln!(md_file, "- **Attention Mask**: `{:?}`", res.attention_mask)?;
        writeln!(md_file, "- **L2 Norm**: `{:.6}` (Unit Sphere verified)", res.l2_norm)?;
        writeln!(md_file, "- **Vector Dimension**: `{}`", res.d_model)?;
        writeln!(md_file, "\n**Embedding Preview (First 8 dims):**")?;
        writeln!(md_file, "```json\n{:?}\n```", res.embedding_sample)?;
        writeln!(md_file, "\n**Complete 64-Dimensional Dense Vector:**")?;
        writeln!(md_file, "```json\n{:?}\n```", res.embedding_full)?;
        writeln!(md_file, "\n---\n")?;
    }

    if !similarities.is_empty() {
        writeln!(md_file, "## Pairwise Semantic Cosine Similarities\n")?;
        writeln!(md_file, "| Sentence A | Sentence B | Cosine Similarity | Semantic Interpretation |")?;
        writeln!(md_file, "|---|---|---|---|")?;
        for (a, b, sim) in similarities {
            let label = if *sim > 0.70 {
                " High Semantic Match (Duplicate / Paraphrase)"
            } else if *sim > 0.30 {
                " Moderate Contextual Overlap"
            } else {
                " Low Similarity / Distinct Topic"
            };
            writeln!(md_file, "| \"{}\" | \"{}\" | **{:.4}** | {} |", a, b, sim, label)?;
        }
    }

    println!(" [FILE SAVED] Formatted presentation report saved to: {}", md_file_path);
    Ok(())
}

fn print_header() {
    println!(r#"
╔═══════════════════════════════════════════════════════════════════════════╗
║         SENTENCE TRANSFORMER FROM SCRATCH IN RUST (POC)                   ║
║      Semantic Search & Document Deduplication Embeddings Engine           ║
╚═══════════════════════════════════════════════════════════════════════════╝
"#);
}

fn run_demo_benchmark(model: &SentenceTransformer) -> (Vec<SentenceEmbeddingResult>, Vec<(String, String, f32)>) {
    println!("-------------------------------------------------------------------");
    println!(" [DEMO] Running Automated Benchmark on Representative Pairs");
    println!("-------------------------------------------------------------------");

    let test_sentences = vec![
        "Deep learning models use neural networks to learn representations",
        "Artificial intelligence leverages neural architectures for representation learning",
        "Vector databases store embeddings for high dimensional nearest neighbor search",
        "The cat is resting on the living room rug",
    ];

    let mut results = Vec::new();
    for s in &test_sentences {
        let res = model.encode(s);
        println!("\n▶ Text: \"{}\"", res.text);
        println!("  • Tokens: {:?}", res.tokens);
        println!("  • Token IDs: {:?}", res.token_ids);
        println!("  • Embedding Dimension: {}", res.d_model);
        println!("  • Vector Preview [0..8]: {:?}", res.embedding_sample);
        println!("  • Vector L2 Norm: {:.4}", res.l2_norm);
        results.push(res);
    }

    println!("\n-------------------------------------------------------------------");
    println!(" [COSINE SIMILARITY EVALUATION]");
    println!("-------------------------------------------------------------------");

    let pairs = vec![
        (test_sentences[0], test_sentences[1], "Paraphrase Pair (Expected: HIGH)"),
        (test_sentences[0], test_sentences[2], "Related Technical Pair (Expected: MEDIUM/LOW)"),
        (test_sentences[0], test_sentences[3], "Unrelated Domain Pair (Expected: LOW)"),
    ];

    let mut similarity_records = Vec::new();
    for (s1, s2, desc) in pairs {
        let (sim, _, _) = model.compare(s1, s2);
        println!("Pair: \"{}\"\n  vs: \"{}\"", s1, s2);
        println!("  • Description: {}", desc);
        println!("  • Cosine Similarity: {:.4}\n", sim);
        similarity_records.push((s1.to_string(), s2.to_string(), sim));
    }

    (results, similarity_records)
}

fn main() -> io::Result<()> {
    print_header();

    let mut model = build_and_train_model();
    let args: Vec<String> = env::args().collect();

    let mut all_results = Vec::new();
    let mut all_sims = Vec::new();

    // Check if arguments were passed directly on CLI
    if args.len() > 1 {
        let input_text = args[1..].join(" ");
        // Ensure new words are in vocab
        model.tokenizer.build_vocab(&[&input_text]);
        model.update_vocab_size();

        let res = model.encode(&input_text);
        println!("\n=======================================================");
        println!(" [CLI INPUT ENCODED]");
        println!("=======================================================");
        println!(" • Input: \"{}\"", res.text);
        println!(" • Tokens: {:?}", res.tokens);
        println!(" • Embedding Sample [0..8]: {:?}", res.embedding_sample);
        println!(" • L2 Norm: {:.4}", res.l2_norm);
        println!("=======================================================\n");
        all_results.push(res);
    } else {
        // Run demo test first
        let (demo_results, demo_sims) = run_demo_benchmark(&model);
        all_results.extend(demo_results);
        all_sims.extend(demo_sims);

        // Interactive mode: Prompt user to enter text or pairs
        println!("\n=======================================================");
        println!(" [INTERACTIVE MODE] Enter your own sentences to embed");
        println!(" Enter a sentence to calculate its embedding vector.");
        println!(" (Type 'exit' or press Enter on empty line to finish)");
        println!("=======================================================\n");

        let stdin = io::stdin();
        let mut handle = stdin.lock();

        loop {
            print!("Enter sentence > ");
            io::stdout().flush()?;
            let mut line = String::new();
            if handle.read_line(&mut line)? == 0 {
                break;
            }
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.eq_ignore_ascii_case("exit") {
                break;
            }

            // Register words in tokenizer
            model.tokenizer.build_vocab(&[trimmed]);
            model.update_vocab_size();

            let res = model.encode(trimmed);
            println!("\n--- Vector Embedding Generated ---");
            println!("Text: \"{}\"", res.text);
            println!("Tokens: {:?}", res.tokens);
            println!("Vector Preview (First 8 dims): {:?}", res.embedding_sample);
            println!("Full 64-dim Vector Length: {}", res.embedding_full.len());
            println!("L2 Norm: {:.4}\n", res.l2_norm);

            all_results.push(res);
        }
    }

    // Save all computed embeddings and comparisons to files
    save_embeddings_to_files(&all_results, &all_sims)?;

    println!("\n All done! You can now present the architecture and the generated embeddings file to the panel.\n");
    Ok(())
}
